---
- hosts: all
  become: yes
  tasks:
  - name: set hostname
    template:
      src: hostname.j2
      dest: /etc/hostname
  - name: restart system
      shell: reboot
  - name: waiting for server to come back
      local_action: wait_for host= {{ ansible_ssh_host }} state=started