---
- hosts: all
  become: yes
  tasks:
  - name: set hostname
    template:
      src: hostname.j2
      dest: /etc/hostname
  - name: restart system
    shell: sleep 2s && reboot && sleep 30s
    async: 1
    poll: 0
  - name: waiting for server to come back
    local_action: wait_for host= {{ ansible_default_ipv4.address }} state=started port=22 timeout=30 delay=15 connect=15