---
- hosts: all
  become: yes
  tasks:
  - name: upgrade
    apt:
      upgrade: yes
  - name: restart system
    shell: sleep 2s && reboot && sleep 30s
    async: 1
    poll: 0
  - name: waiting for server to come back
    become: false
    local_action: wait_for host= {{ inventory_hostname }} state=started port=22 timeout=30 delay=15 connect=15