---
- hosts: all
  become: yes
  tasks:
  - name: install aptitude
    apt: name=aptitude state=present update_cache=yes
  - name: upgraded test a other method
    raw: apt-get upgrade
  - name: test apt-get upgrade
    apt: update_cache=yes upgrade=yes
  - name: Execute reboot when kernel has changed
    shell: sleep 5 && reboot
    async: 1
    ignore_errors: true
    register: reboot
  - name: Wait for servers reboot task to execute
    pause:
     seconds: 60
    when: reboot is defined
  - name: Wait for provisioned server
    delegate_to: localhost
    wait_for:
     host: "{{ inventory_hostname }}"
     port: 22
     state: started
     timeout: 300
     connect_timeout: 20
    when: reboot is defined
  - name: install vim
    apt: name=vim state=present update_cache=yes