---
- hosts: all
  become: yes
  tasks:
  - name: install aptitude
    apt: name=aptitude state=present update_cache=yes
  - name: upgraded test a other method
    raw: apt-get upgrade
  - name: test apt-get upgrade
    apt: update_cache=yes upgrade=yes
  - name: restart system
#    shell: sleep 2s && reboot && sleep 30s
    shell: sleep 2 && shutdown -r now "Ansible package updates triggered"
    async: 0
    poll: 0
  - name: waiting for server to come back
    local_action: wait_for host={{ inventory_hostname }} state=started port=22 timeout=30 delay=15 connect=45
  - name: install vim
    apt: name=vim state=present update_cache=yes