---
- hosts: all
  become: yes
  tasks:
  - name: install vim
    apt: name=vim state=present update_cache=yes
  - name: upgraded because apt:upgrade is not support by ubuntu/debian
    raw: apt-get upgrade
  - name: test apt-get upgrade
    apt: update_cache=yes upgrade=apt-upgrade
  - name: restart system
    shell: sleep 2s && reboot && sleep 30s
    async: 1
    poll: 0
  - name: waiting for server to come back
    become: false
    local_action: wait_for host= {{ inventory_hostname }} state=started port=22 timeout=30 delay=15 connect=15