---
- hosts: ios_switches
  gather_facts: no
  tasks:
  - name: set hostname
    ios_config:
      lines: hostname {{ inventory_hostname_short }}
      provider:
        host: 192.168.1.120
        username: admin
        password: s3cr3t
        authorize: true
        auth_pass: 3n4bl3s3cr3t
      backup: true
      save: true
  - debug: msg="Der Variablename ist {{ inventory_hostname }}"
